name: DungeonRealms
main: net.dungeonrealms.DungeonRealms
version: ${project.parent.version}
authors: [xFinityPro, Vawke]
website: http://www.dungeonrealms.org
depend: [WorldGuard, BossBarAPI, ProtocolLib, BungeeTabListPlus]
description: The new and improved DungeonRealms!